"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from .sdkconfiguration import SDKConfiguration
from kdmistralai.conversations import Conversations
from kdmistralai.kdmistral_agents import KdMistralAgents


class Beta(BaseSDK):
    conversations: Conversations
    r"""(beta) Conversations API"""
    agents: KdMistralAgents
    r"""(beta) Agents API"""

    def __init__(self, sdk_config: SDKConfiguration) -> None:
        BaseSDK.__init__(self, sdk_config)
        self.sdk_configuration = sdk_config
        self._init_sdks()

    def _init_sdks(self):
        self.conversations = Conversations(self.sdk_configuration)
        self.agents = KdMistralAgents(self.sdk_configuration)
