workflowVersion: 1.0.0
speakeasyVersion: 1.568.2
sources:
    mistral-azure-source:
        inputs:
        -   location: ./mistral-openapi-azure.yaml
    mistral-google-cloud-source:
        inputs:
        -   location: ./mistral-openapi-google-cloud.yaml
    mistral-openapi:
        inputs:
        -   location: ./mistral-openapi-main.yaml
targets:
    mistralai-azure-sdk:
        target: python
        source: mistral-azure-source
        output: ./packages/mistralai_azure
        publish:
            pypi:
                token: $pypi_token
    mistralai-gcp-sdk:
        target: python
        source: mistral-google-cloud-source
        output: ./packages/mistralai_gcp
        publish:
            pypi:
                token: $pypi_token
    mistralai-sdk:
        target: python
        source: mistral-openapi
        publish:
            pypi:
                token: $pypi_token
