"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from kdmistralai.types import BaseModel
from kdmistralai.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal, Optional
from typing_extensions import Annotated, TypedDict


class AudioLanguageChunkTypedDict(TypedDict):
    r"""Language identifier, formatted as an ISO 639-1 tag."""

    audio_language: str
    type: Literal["audio_language"]


class AudioLanguageChunk(BaseModel):
    r"""Language identifier, formatted as an ISO 639-1 tag."""

    audio_language: str

    TYPE: Annotated[
        Annotated[
            Optional[Literal["audio_language"]],
            AfterValidator(validate_const("audio_language")),
        ],
        pydantic.Field(alias="type"),
    ] = "audio_language"
