"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from kdmistralai.types import BaseModel
from kdmistralai.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class JobsAPIRoutesBatchGetBatchJobRequestTypedDict(TypedDict):
    job_id: str


class JobsAPIRoutesBatchGetBatchJobRequest(BaseModel):
    job_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
