"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .transcriptionsegmentchunk import (
    TranscriptionSegmentChunk,
    TranscriptionSegmentChunkTypedDict,
)
from kdmistralai.types import BaseModel
from kdmistralai.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal, Optional
from typing_extensions import Annotated, TypedDict


class TranscriptionStreamSegmentDeltaTypedDict(TypedDict):
    data: TranscriptionSegmentChunkTypedDict
    type: Literal["transcription.segment"]


class TranscriptionStreamSegmentDelta(BaseModel):
    data: TranscriptionSegmentChunk

    TYPE: Annotated[
        Annotated[
            Optional[Literal["transcription.segment"]],
            AfterValidator(validate_const("transcription.segment")),
        ],
        pydantic.Field(alias="type"),
    ] = "transcription.segment"
