"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .textchunk import TextChunk, TextChunkTypedDict
from kdmistralai.types import BaseModel
from kdmistralai.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal, Optional
from typing_extensions import Annotated, TypedDict


class TranscriptionStreamTextDeltaTypedDict(TypedDict):
    data: TextChunkTypedDict
    type: Literal["transcription.text.delta"]


class TranscriptionStreamTextDelta(BaseModel):
    data: TextChunk

    TYPE: Annotated[
        Annotated[
            Optional[Literal["transcription.text.delta"]],
            AfterValidator(validate_const("transcription.text.delta")),
        ],
        pydantic.Field(alias="type"),
    ] = "transcription.text.delta"
