"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .audiolanguagechunk import AudioLanguageChunk, AudioLanguageChunkTypedDict
from kdmistralai.types import BaseModel
from kdmistralai.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal, Optional
from typing_extensions import Annotated, TypedDict


class TranscriptionStreamLanguageTypedDict(TypedDict):
    data: AudioLanguageChunkTypedDict
    r"""Language identifier, formatted as an ISO 639-1 tag."""
    type: Literal["transcription.language"]


class TranscriptionStreamLanguage(BaseModel):
    data: AudioLanguageChunk
    r"""Language identifier, formatted as an ISO 639-1 tag."""

    TYPE: Annotated[
        Annotated[
            Optional[Literal["transcription.language"]],
            AfterValidator(validate_const("transcription.language")),
        ],
        pydantic.Field(alias="type"),
    ] = "transcription.language"
