"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .transcriptionresponse import TranscriptionResponse, TranscriptionResponseTypedDict
from kdmistralai.types import BaseModel
from kdmistralai.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal, Optional
from typing_extensions import Annotated, TypedDict


class TranscriptionStreamDoneTypedDict(TypedDict):
    data: TranscriptionResponseTypedDict
    type: Literal["transcription.done"]


class TranscriptionStreamDone(BaseModel):
    data: TranscriptionResponse

    TYPE: Annotated[
        Annotated[
            Optional[Literal["transcription.done"]],
            AfterValidator(validate_const("transcription.done")),
        ],
        pydantic.Field(alias="type"),
    ] = "transcription.done"
