"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from kdmistralai.types import BaseModel
from kdmistralai.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal, Optional
from typing_extensions import Annotated, TypedDict


class TranscriptionSegmentChunkTypedDict(TypedDict):
    text: str
    start: float
    end: float
    type: Literal["transcription_segment"]


class TranscriptionSegmentChunk(BaseModel):
    text: str

    start: float

    end: float

    TYPE: Annotated[
        Annotated[
            Optional[Literal["transcription_segment"]],
            AfterValidator(validate_const("transcription_segment")),
        ],
        pydantic.Field(alias="type"),
    ] = "transcription_segment"
